# custom build to include format-encoder plugin
# will be invoked by docker-compose file
# this is did NOT work, but I will leave it since it works OK with JSON logs

FROM caddy:2-builder AS builder

RUN xcaddy build \
    --with github.com/caddyserver/transform-encoder

FROM caddy:2

COPY --from=builder /usr/bin/caddy /usr/bin/caddy