version: '3'
services:
  app:
    build: .
    container_name: django
    restart: always
    # env_file:
    # - .env
    volumes:
      - .:/usr/src/app
      - /home/david/python_projects/mccallie-family-stories/staticfiles:/usr/src/app/staticfiles
      - /home/david/python_projects/mccallie-family-stories/media:/usr/src/app/media
      - /home/david/python_projects/mccallie-family-stories/logs/gunicorn:/usr/src/app/logs/gunicorn
    expose:
      - "8000"
    command: ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "2", "--timeout", "60", "--log-level", "debug"]

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    image: custom-caddy:latest
    container_name: caddy
    restart: always
    # user: 1000:1000  # Run as UID 1000 and GID 1000
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/david/python_projects/mccallie-family-stories/Caddyfile:/etc/caddy/Caddyfile
      - /home/david/python_projects/mccallie-family-stories/staticfiles:/usr/src/app/staticfiles
      - /home/david/python_projects/mccallie-family-stories/logs/caddy:/var/log/caddy
      - caddy_data:/data
      - caddy_config:/config
      

volumes:
  caddy_data:
  caddy_config:
