# Generated by Django 5.0.6 on 2024-05-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_content_alter_story_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='published_date',
        ),
        migrations.AddField(
            model_name='story',
            name='published_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
