# Generated by Django 5.0.6 on 2024-06-01 00:40

import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_remove_story_published_date_story_published_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='story',
            name='summary',
            field=models.CharField(max_length=512, validators=[stories.models.validate_contains_good]),
        ),
    ]
