# Generated by Django 5.0.6 on 2024-06-03 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='story',
        ),
    ]
