# Generated by Django 5.0.6 on 2024-06-12 23:01

import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='story',
            name='summary',
            field=models.TextField(max_length=512, validators=[stories.models.validate_contains_good]),
        ),
    ]
