# Generated by Django 5.0.6 on 2024-06-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_alter_story_content_alter_story_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(max_length=100000),
        ),
    ]
