# Generated by Django 5.0.6 on 2024-09-07 02:41

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_drop_and_auto_create_fts_table'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
